### ISSUE TITLE
Proposal 

### ISSUE THREAD

**Issue by PAVAN-VANAM** [Bhanu-code/OpenLMS#1]
hello @Bhanu-code 

I want to know more requirements and ideas about the project so I can help U to start with this OpenLMS

I want to work on this project Can u assign me?

**Comment by Bhanu-code** [comment]
@PAVAN-VANAM The idea behind OpenLMS is to provide an open source codebase for educational institutes who wants to create and manage their LMS, but want a basic boilder plate SDK to development. Institutions can use the OpenLMS SDK for their personal LMS providing scalability, smoothness, and secuirity managed. Institutional educators can teach, provide materials, conduct tests & assignments etc. Students can see their courses and subjects, complete assignments, give exams & tests, etc.

We need a figma design for the platform with pages like login, dahsboard, enrolled courses, progress, online tests, study materials etc.

So, please anyone who can contribute with a Figma design is welcomed!
