### ISSUE TITLE
[Feature]: Home, Login and Signup Screens

### ISSUE THREAD

**Issue by Reboot2004** [Bhanu-code/OpenLMS#16]
### Description

I would like to help develop figma designs and develop Home, Login and Signup Pages

### Suggested Solution

Figma Design for all three Screens.
Utilize authentication services to implement login and signup functionality

**Comment by Reboot2004** [comment]
Please Assign me this issue with GSSOC extd, Hactoberfest, Hacktoberfest accepted and level labels

**Comment by Bhanu-code** [comment]
@Reboot2004 go ahead. we need figma design asap.

**Comment by Reboot2004** [comment]
https://www.figma.com/design/7WFQvDENPrc7fYdeOmx3yV/Login-Register?node-id=1669-162202&m=dev&t=APzuRtzGaWhOuRw9-1
Suggestions are welcome

**Comment by Bhanu-code** [comment]
@Reboot2004 looks good, add the design to README and push it. Try to develop further designs

**Comment by Reboot2004** [comment]
@Bhanu-code Have created a pull request for the same [here](https://github.com/Bhanu-code/OpenLMS/pull/20)
Will close this issue when the pull request is accepted.
