### ISSUE TITLE
More Requirement Needed

### ISSUE THREAD

**Issue by TseganeshYifruBerta** [Bhanu-code/OpenLMS#3]
I want more information in order to contribute to this project. At least the features needs to be clearly stated. 
I'm exited to contribute to this project.

**Comment by Bhanu-code** [comment]
@TseganeshYifruBerta The idea behind OpenLMS is to provide an open source codebase for educational institutes who wants to create and manage their LMS, but want a basic boilder plate SDK to development. Institutions can use the OpenLMS SDK for their personal LMS providing scalability, smoothness, and secuirity managed. Institutional educators can teach, provide materials, conduct tests & assignments etc. Students can see their courses and subjects, complete assignments, give exams & tests, etc.

We need a figma design for the platform with pages like login, dahsboard, enrolled courses, progress, online tests, study materials etc.

So, please anyone who can contribute with a Figma design is welcomed!

**Comment by Bhanu-code** [comment]
@TseganeshYifruBerta @Vin205 we will be creating a gtihub discussions forum!
