### ISSUE TITLE
[Feature]:  Implementing oAuth like google, facebook, twitter and github

### ISSUE THREAD

**Issue by Edasgh** [Bhanu-code/OpenLMS#30]
### Description

Buttons are there in ui but implementation is not yet done i would like to work on this issue. 
Please assign this issue to me under gssoc-ext, hacktoberfest-accepted and a relevant level labels
![Screenshot 2024-10-24 195819](https://github.com/user-attachments/assets/36960c67-cd8b-4af2-8a92-c53ba90542ec)

### Suggested Solution

I will implement the oauth with google, facebook and with apple both in sign up & sign in

**Comment by Raj100** [comment]
Do one thing lets split this issue
You do Facebook and Google I will do for Apple and twitter ! just fetch the username and email from the apps

**Comment by Raj100** [comment]
@Bhanu-code  Please assign this issue and Add ggoc-ext and hacktober fest accepted tags

**Comment by Bhanu-code** [comment]
@Raj100 @Edasgh ok, you both can collaborate.

**Comment by Edasgh** [comment]
> @Raj100 @Edasgh ok, you both can collaborate.

Ok

**Comment by Edasgh** [comment]
@Bhanu-code please check the PR : https://github.com/Bhanu-code/OpenLMS/pull/33
