### ISSUE TITLE
Missing contributing.md file

### ISSUE THREAD

**Issue by archanasingh11** [Bhanu-code/OpenLMS#5]
**Description:**

The `CONTRIBUTING.md` file is missing from the OpenLMS repository. This file is essential for guiding new contributors through the process of setting up the project, adhering to coding standards, and submitting pull requests. Without it, contributors may lack clarity on how to effectively contribute to the project, which could lead to inconsistencies and confusion.

I recommend adding a `CONTRIBUTING.md` file to outline:
- Steps for setting up the repository locally.
- Branching and submission of pull requests.
- Code style guidelines and best practices.
- How to report issues and propose new features.

please @Bhanu-code  assign me this task with labels "GSSOC-Ext", "Hacktoberfest-accepted" and"level1".

**Comment by AnujSaha0111** [comment]
Can you please assign it to me? I want to work on it.
Can you also add gssoc-ext label

**Comment by archanasingh11** [comment]
@Bhanu-code  I want to work on this project Y have u closed this project

**Comment by Bhanu-code** [comment]
@archanasingh11 that's actually something which should be done by project admin
